services:
  redis:
    image: redis:7
    container_name: redis-php
    ports: 
      - "6379:6379"
    networks:
      - php-network

  postgres:
    image: postgres:17
    container_name: postgres-php
    environment:
      - POSTGRES_DB: auth-db
      - POSTGRES_USER: user
      - POSTGRES_PASSWORD: password
    ports:
      - "5433:5432" 
    networks:
      - php-network

  auth-api:
    build: .
    container_name: php-app
    depends_on:
      - redis
      - postgres
    ports:
      - "8000:8000"
    networks:
      - php-network

networks:
  php-network:
    driver: bridge